import {
  PostVisibility,
  PostStatus,
  ConnectionType,
} from '@/apollo/generated/types';

const existingPost = {
  _id: '62fb43f8b5900e000d29e8a2',
  uid: {
    SocialHallTCAccepted: false,
    _id: '62f3b13211ec9b000e5c1060',
    ageGroup: null,
    bio: null,
    citizenship: null,
    connection: ConnectionType.None,
    connections: [],
    createdAt: '2022-08-10T13:22:58.514Z',
    creditCheckResult: null,
    email: 'testnoumena21@ravikiran.com',
    firstName: 'Ravikiran',
    freelancingExperience: null,
    kycResult: null,
    lastLoginAt: null,
    lastName: 'WorkExp',
    location: null,
    metadata: [
      {
        additionalInfo: null,
        changeOn: '2022-08-10T13:23:53.998Z',
        changedBy: '619f5f21433523318c243250',
        moreInfo: '',
        reason: '',
        statusFrom: 'PENDING',
        statusTo: 'ACTIVE',
      },
    ],
    middleName: null,
    phone: null,
    profile: {
      _id: '62f3b13211ec9b000e5c1061',
      profilePicture: null,
      profilePictureThumbnail: null,
    },
    profileUrl: null,
    referralCode: null,
    roles: [],
    skills: [
      {
        _id: '61c182a5e617a7178a228dc8',
        icon: 'IT Consulting',
        name: 'IT Consulting',
      },
      {
        _id: '61c182a5e617a744c5228dce',
        icon: 'Other IT & Engineering  Services',
        name: 'Other IT & Engineering  Services',
      },
    ],
    status: 'REGISTERED',
    title: null,
    unreadConnectionCount: 0,
    updatedAt: '2022-08-10T13:25:47.606Z',
    userOwnReferralCode: '4870',
    userStatus: 'ACTIVE',
    username: 'rworkexp',
    visibility: {
      email: 'USER',
      location: 'ALL',
      phone: 'USER',
    },
    visibleTo: [],
  },
  text: 'hi new post',
  post: {
    category: null,
    content: null,
    thumbnail: null,
    resolutions: [],
  },
  reactions: [],
  userReaction: null,
  reactionsCount: 0,
  commentsCount: 0,
  comments: [],
  visibility: PostVisibility.Connection,
  postStatus: PostStatus.Accepted,
  reports: [],
  isPinned: false,
  pinnedTimestamp: null,
  createdAt: '2022-08-16T07:15:04.526Z',
  updatedAt: '2022-08-16T07:15:04.526Z',
  tags: [],
  chamberId: '628e70b4beea5a017a6e362e',
};

export default existingPost;
