fragment ElementInnerOutput on ElementInnerOutput {
  bodyContent
  headerContent
  position
  isDeleted
  bodyContentJson
  percentCompleted
  customPreviewPosition
  isCustomPreviewVisible
  meta
}
