fragment LinkedNoum on SpaceOutput {
  _id
  name
  title
  profileImage
  type
  permission
  followersCount
  connectionId
  projectType
  link {
    _id
    status
    linkedNoumsCount
  }
  category {
    _id
    name
  }
  connectionsCount
  createdAt
  ...SpaceConnectedMembersCount
}

fragment SpaceConnectedMembersCount on SpaceOutput {
  members(input: { statuses: CONNECTED }) {
    count
  }
}
