fragment NoumMembershipStatus on NoumMembershipStatus {
  _id
  status
  connectedAt
  status
  role {
    ...NoumMemberRoleBasic
  }
  invitationSentFrom {
    ...UserBasicOutput
  }
  rolePromotionToApprove {
    ...NoumMemberRoleForPromotion
  }
}
