import { UpdateElementDocument } from '@/apollo/graphql';

export const mockdata = [
  {
    request: {
      query: UpdateElementDocument,
      variables: {
        id: '6269b49b2314503140794492',
        input: {
          bodyContentJson: '',
          bodyContentType: 'JSON',
          elementId: '62694c80231450a11478ca33',
          position: null,
          status: 'UNSAVED',
        },
      },
    },
    result: () => ({
      data: {
        updateElement: {
          _id: '62694c80231450a11478ca33',
          description: null,
          publishedAt: '2022-06-15T05:41:43.639Z',
          updatedAt: '2022-06-15T08:06:16.792Z',
          elements: [
            {
              _id: '62694c80231450a11478ca33',
              bodyContent: null,
              bodyContentJson: null,
              bodyContentType: 'TEXT',
              draft: null,
              elementType: 'HOME',
              headerContent: null,
              position: 8,
              status: 'PUBLISHED',
              tempStatus: null,
              unSaved: null,
              viewOnly: null,
              __typename: 'ElementOutput',
            },
            {
              _id: '62694c8023145070f278ca34',
              bodyContent: null,
              bodyContentJson: null,
              bodyContentType: 'TEXT',
              draft: null,
              elementType: 'INVITATION',
              headerContent: null,
              position: 5,
              status: 'PUBLISHED',
              tempStatus: null,
              unSaved: null,
              viewOnly: null,
              __typename: 'ElementOutput',
            },
            {
              _id: '62694c80231450948078ca35',
              bodyContent: null,
              bodyContentJson: null,
              bodyContentType: 'TEXT',
              draft: null,
              elementType: 'MESSAGE',
              headerContent: null,
              position: 9,
              status: 'PUBLISHED',
              tempStatus: null,
              unSaved: null,
              viewOnly: null,
              __typename: 'ElementOutput',
            },
          ],
          institution: 'NOUMENA',
          name: 'HOME Chamber',
          networks: [],
          permission: 'POST_CREATE',
          profileImage: null,
          status: 'PUBLISHED',
          title: null,
          token: {
            _id: '62694c80231450406178ca3b',
            count: 0,
            walletId: null,
            __typename: 'Token',
          },
          type: 'HOME',
          uid: {
            SocialHallTCAccepted: false,
            _id: '625e6e2465ff0cd24e83ab37',
            ageGroup: null,
            bio: null,
            citizenship: null,
            connection: 'none',
            connections: [],
            createdAt: '2022-04-19T08:09:08.331Z',
            creditCheckResult: null,
            email: 'rajasekhar517@gmail.com',
            firstName: 'Raja',
            freelancingExperience: null,
            kycResult: null,
            lastLoginAt: '2022-06-14T13:09:52.436Z',
            lastName: 'Sekhar',
            location: null,
            metadata: [
              {
                additionalInfo: null,
                changeOn: '2022-04-26T13:42:41.094Z',
                changedBy: '619f5f21433523318c243250',
                moreInfo: '',
                reason: '',
                statusFrom: 'PENDING',
                statusTo: 'ACTIVE',
                __typename: 'LogsOutput',
              },
            ],
            middleName: null,
            phone: null,
            profile: {
              _id: '625e6e2465ff0ccee783ab38',
              profilePicture: null,
              profilePictureThumbnail: null,
              __typename: 'ProfileOutput',
            },
            profileUrl: null,
            referralCode: null,
            roles: [],
            skills: [
              {
                _id: '61c182a5e617a744c5228dce',
                icon: 'Other IT & Engineering  Services',
                name: 'Other IT & Engineering  Services',
                __typename: 'Skill',
              },
            ],
            status: 'REGISTERED',
            title: null,
            unreadConnectionCount: 0,
            updatedAt: '2022-06-14T13:09:52.436Z',
            userOwnReferralCode: '3641',
            userStatus: 'ACTIVE',
            username: 'rsekhar1',
            visibility: {
              email: 'USER',
              location: 'ALL',
              phone: 'USER',
              __typename: 'UserOutputVisibility',
            },
            visibleTo: [],
            __typename: 'UserOutput',
          },
          __typename: 'SpaceOutput',
        },
      },
    }),
  },
];
