import { AutoCreateOrUnarchiveNoumAfterCheckout } from '@/screens/Chamber/components/AutoCreateOrUnarchiveNoumAfterCheckout/AutoCreateOrUnarchiveNoumAfterCheckout';

export default AutoCreateOrUnarchiveNoumAfterCheckout;
