import { BodyContentEnum, ElementStatusEnum } from '../generated/types';
import { GetSpaceByIdDocument, type SpaceOutputFragment } from '../graphql';

const spaceId = '6241a26b23700ef26c82b67e';

export const getSpaceByIdMock = {
  request: {
    query: GetSpaceByIdDocument,
    variables: {
      id: spaceId,
    },
  },
  result: () => ({ data: { spaceMockData } }),
};

export const spaceMockData: SpaceOutputFragment = {
  __typename: 'SpaceOutput',
  _id: '623951b6175c6d45f85d8e27',
  description: null,
  elements: [
    {
      __typename: 'ElementOutput',
      _id: '623951b6175c6d8f5e5d8e1f',
      bodyContent: null,
      bodyContentJson: null,
      bodyContentType: BodyContentEnum.Text,
      draft: null,
      elementType: 'HOME',
      headerContent: null,
      position: 1,
      status: 'PUBLISHED',
      tempStatus: ElementStatusEnum.Unsaved,
      unSaved: {
        __typename: 'ElementInnerOutput',
        bodyContent: 'xxxxxxxxxxxxxxxxxxxxxxxxxxx',
        bodyContentJson: null,
        headerContent: null,
        isDeleted: null,
        position: 1,
      },
      viewOnly: true,
    },
    {
      __typename: 'ElementOutput',
      _id: '623951b6175c6d44c55d8e20',
      bodyContent: null,
      bodyContentJson: null,
      bodyContentType: BodyContentEnum.Text,
      draft: null,
      elementType: 'INVITATION',
      headerContent: null,
      position: 2,
      status: 'PUBLISHED',
      tempStatus: ElementStatusEnum.Unsaved,
      unSaved: {
        __typename: 'ElementInnerOutput',
        bodyContent: 'xxxxxxxxxxxxxxxxxxxxxxxxxxx',
        bodyContentJson: null,
        headerContent: null,
        isDeleted: null,
        position: 2,
      },
      viewOnly: true,
    },
    {
      __typename: 'ElementOutput',
      _id: '623951b6175c6dd4505d8e21',
      bodyContent: null,
      bodyContentJson: null,
      bodyContentType: BodyContentEnum.Text,
      draft: null,
      elementType: 'MESSAGE',
      headerContent: null,
      position: 3,
      status: 'PUBLISHED',
      tempStatus: ElementStatusEnum.Unsaved,
      unSaved: {
        __typename: 'ElementInnerOutput',
        bodyContent: '000000',
        bodyContentJson: null,
        headerContent: null,
        isDeleted: null,
        position: 3,
      },
      viewOnly: false,
    },
    {
      __typename: 'ElementOutput',
      _id: '623951b6175c6dbf5d5d8e22',
      bodyContent: null,
      bodyContentJson: null,
      bodyContentType: BodyContentEnum.Text,
      draft: null,
      elementType: 'CONNECTION',
      headerContent: null,
      position: 4,
      status: 'PUBLISHED',
      tempStatus: null,
      unSaved: null,
      viewOnly: false,
    },
    {
      __typename: 'ElementOutput',
      _id: '623951b6175c6d97575d8e23',
      bodyContent: null,
      bodyContentJson: null,
      bodyContentType: BodyContentEnum.Text,
      draft: null,
      elementType: 'SKILLS',
      headerContent: null,
      position: 5,
      status: 'PUBLISHED',
      tempStatus: null,
      unSaved: null,
      viewOnly: false,
    },
    {
      __typename: 'ElementOutput',
      _id: '623951b6175c6d64155d8e24',
      bodyContent: null,
      bodyContentJson: null,
      bodyContentType: BodyContentEnum.Text,
      draft: null,
      elementType: 'USERPOSTS',
      headerContent: null,
      position: 6,
      status: 'PUBLISHED',
      tempStatus: null,
      unSaved: null,
      viewOnly: false,
    },
    {
      __typename: 'ElementOutput',
      _id: '623951b6175c6d365c5d8e25',
      bodyContent: '{"www":"linked.com"}',
      bodyContentJson: null,
      bodyContentType: BodyContentEnum.Text,
      draft: null,
      elementType: 'USERNETWORK',
      headerContent: null,
      position: 7,
      status: 'PUBLISHED',
      tempStatus: null,
      unSaved: null,
      viewOnly: false,
    },
    {
      __typename: 'ElementOutput',
      _id: '6242029651984034f6f05f88',
      bodyContent: null,
      bodyContentJson: null,
      bodyContentType: BodyContentEnum.Text,
      draft: null,
      elementType: 'HOME',
      headerContent: null,
      position: null,
      status: 'PUBLISHED',
      tempStatus: ElementStatusEnum.Unsaved,
      unSaved: {
        __typename: 'ElementInnerOutput',
        bodyContent: 'xxxxxxxxxxxxxxxxxxxxxxxxxxx',
        bodyContentJson: null,
        headerContent: null,
        isDeleted: null,
        position: 1,
      },
      viewOnly: true,
    },
  ],
  institution: 'NOUMENA',
  name: 'HOME Chamber',
  networks: [],
  permission: 'POST_CREATE',
  profileImage: null,
  status: 'PUBLISHED',
  title: null,
  token: {
    __typename: 'Token',
    _id: '623951b6175c6d45f85d8e27',
    count: 0,
  },
  type: 'HOME',
  uid: {
    __typename: 'UserOutput',
    _id: '6232f2aefd028201aff18b43',
    bio: null,
    email: 'mark@noumena.global',
    firstName: 'Mark',
    lastName: 'F',
    location: null,
    middleName: null,
    phone: null,
    profile: {
      __typename: 'ProfileOutput',
      _id: '6232f2aefd0282bedff18b44',
      profilePicture: null,
      profilePictureThumbnail: null,
    },
    skills: [
      {
        __typename: 'Skill',
        _id: '61c180f0e617a72e07228c3b',
        icon: 'Web and Mobile Application Development',
        name: 'Web and Mobile Application Development',
      },
    ],
    status: 'REGISTERED',
    title: null,
    userStatus: 'ACTIVE',
    username: 'mf',
  },
};
