const MAX_OTHER_GOAL_CHARACTERS = 3000;

const MAX_AUDIENCE_CHARACTERS = 1000;

const MAX_TITLE_CHARACTERS = 100;

export const constants = {
  MAX_OTHER_GOAL_CHARACTERS,
  MAX_AUDIENCE_CHARACTERS,
  MAX_TITLE_CHARACTERS,
};
