import { type SpaceOutputFragment } from '@/apollo/graphql';

export const getSpaceById: SpaceOutputFragment = {
  __typename: 'SpaceOutput',
  _id: '624cfaf0cb8e6a7d595b5fe7',
  percentCompleted: 0,
  projectType: 'PUBLIC',
  description: null,
  followersCount: 0,
  connectionsCount: 0,
  isFollowing: false,
  publishedAt: '2022-05-20T15:13:57.573Z',
  updatedAt: '2022-05-26T05:25:26.555Z',
  elements: [],
  name: 'Sample Space',
  permission: 'POST_CREATE',
  profileImage: null,
  status: 'DRAFT',
  title: 'My New Space',
  token: {
    __typename: 'Token',
    _id: '624cfaf0cb8e6a7d595b5fe7',
    count: 0,
  },
  type: 'WORK',
  uid: {
    __typename: 'UserOutput',
    _id: '6241a26b23700ef26c82b67e',
    bio: null,
    email: 'radheym@noumena.global',
    firstName: 'Radhey',
    lastName: 'M',
    location: null,
    middleName: null,
    phone: null,
    profile: {
      __typename: 'ProfileOutput',
      _id: '6241a26b23700eff1a82b67f',
      profilePicture: null,
      profilePictureThumbnail: null,
    },
    status: 'REGISTERED',
    title: null,
    userStatus: 'PENDING',
    skills: null,
    chamber: null,
  },
  category: null,
  link: null,
};
