import { AllCurrencyEnum } from '@/apollo/generated/types';

export default {
  [AllCurrencyEnum.Usd]: {
    symbol: '$',
    name: 'US Dollar',
    symbol_native: '$',
    decimal_digits: 2,
    rounding: 0,
    name_plural: 'US dollars',
  },
  [AllCurrencyEnum.Cad]: {
    symbol: 'CA$',
    name: 'Canadian Dollar',
    symbol_native: '$',
    decimal_digits: 2,
    rounding: 0,
    name_plural: 'Canadian dollars',
  },
  [AllCurrencyEnum.Eur]: {
    symbol: '€',
    name: 'Euro',
    symbol_native: '€',
    decimal_digits: 2,
    rounding: 0,
    name_plural: 'euros',
  },
  [AllCurrencyEnum.Aed]: {
    symbol: 'AED',
    name: 'United Arab Emirates Dirham',
    symbol_native: 'د.إ.‏',
    decimal_digits: 2,
    rounding: 0,
    name_plural: 'UAE dirhams',
  },
  [AllCurrencyEnum.Afn]: {
    symbol: 'Af',
    name: 'Afghan Afghani',
    symbol_native: '؋',
    decimal_digits: 0,
    rounding: 0,
    name_plural: 'Afghan Afghanis',
  },
  [AllCurrencyEnum.All]: {
    symbol: 'ALL',
    name: 'Albanian Lek',
    symbol_native: 'Lek',
    decimal_digits: 0,
    rounding: 0,
    name_plural: 'Albanian lekë',
  },
  [AllCurrencyEnum.Amd]: {
    symbol: 'AMD',
    name: 'Armenian Dram',
    symbol_native: 'դր.',
    decimal_digits: 0,
    rounding: 0,
    name_plural: 'Armenian drams',
  },
  [AllCurrencyEnum.Ars]: {
    symbol: 'AR$',
    name: 'Argentine Peso',
    symbol_native: '$',
    decimal_digits: 2,
    rounding: 0,
    name_plural: 'Argentine pesos',
  },
  [AllCurrencyEnum.Aud]: {
    symbol: 'AU$',
    name: 'Australian Dollar',
    symbol_native: '$',
    decimal_digits: 2,
    rounding: 0,
    name_plural: 'Australian dollars',
  },
  [AllCurrencyEnum.Azn]: {
    symbol: 'man.',
    name: 'Azerbaijani Manat',
    symbol_native: 'ман.',
    decimal_digits: 2,
    rounding: 0,
    name_plural: 'Azerbaijani manats',
  },
  [AllCurrencyEnum.Bam]: {
    symbol: 'KM',
    name: 'Bosnia-Herzegovina Convertible Mark',
    symbol_native: 'KM',
    decimal_digits: 2,
    rounding: 0,
    name_plural: 'Bosnia-Herzegovina convertible marks',
  },
  [AllCurrencyEnum.Bdt]: {
    symbol: 'Tk',
    name: 'Bangladeshi Taka',
    symbol_native: '৳',
    decimal_digits: 2,
    rounding: 0,
    name_plural: 'Bangladeshi takas',
  },
  [AllCurrencyEnum.Bgn]: {
    symbol: 'BGN',
    name: 'Bulgarian Lev',
    symbol_native: 'лв.',
    decimal_digits: 2,
    rounding: 0,
    name_plural: 'Bulgarian leva',
  },
  [AllCurrencyEnum.Bhd]: {
    symbol: 'BD',
    name: 'Bahraini Dinar',
    symbol_native: 'د.ب.‏',
    decimal_digits: 3,
    rounding: 0,
    name_plural: 'Bahraini dinars',
  },
  [AllCurrencyEnum.Bif]: {
    symbol: 'FBu',
    name: 'Burundian Franc',
    symbol_native: 'FBu',
    decimal_digits: 0,
    rounding: 0,
    name_plural: 'Burundian francs',
  },
  [AllCurrencyEnum.Bnd]: {
    symbol: 'BN$',
    name: 'Brunei Dollar',
    symbol_native: '$',
    decimal_digits: 2,
    rounding: 0,
    name_plural: 'Brunei dollars',
  },
  [AllCurrencyEnum.Bob]: {
    symbol: 'Bs',
    name: 'Bolivian Boliviano',
    symbol_native: 'Bs',
    decimal_digits: 2,
    rounding: 0,
    name_plural: 'Bolivian bolivianos',
  },
  [AllCurrencyEnum.Brl]: {
    symbol: 'R$',
    name: 'Brazilian Real',
    symbol_native: 'R$',
    decimal_digits: 2,
    rounding: 0,
    name_plural: 'Brazilian reals',
  },
  [AllCurrencyEnum.Bwp]: {
    symbol: 'BWP',
    name: 'Botswanan Pula',
    symbol_native: 'P',
    decimal_digits: 2,
    rounding: 0,
    name_plural: 'Botswanan pulas',
  },
  [AllCurrencyEnum.Byn]: {
    symbol: 'Br',
    name: 'Belarusian Ruble',
    symbol_native: 'руб.',
    decimal_digits: 2,
    rounding: 0,
    code: 'BYN',
    name_plural: 'Belarusian rubles',
  },
  [AllCurrencyEnum.Bzd]: {
    symbol: 'BZ$',
    name: 'Belize Dollar',
    symbol_native: '$',
    decimal_digits: 2,
    rounding: 0,
    name_plural: 'Belize dollars',
  },
  [AllCurrencyEnum.Cdf]: {
    symbol: 'CDF',
    name: 'Congolese Franc',
    symbol_native: 'FrCD',
    decimal_digits: 2,
    rounding: 0,
    name_plural: 'Congolese francs',
  },
  [AllCurrencyEnum.Chf]: {
    symbol: 'CHF',
    name: 'Swiss Franc',
    symbol_native: 'CHF',
    decimal_digits: 2,
    rounding: 0.05,
    name_plural: 'Swiss francs',
  },
  [AllCurrencyEnum.Clp]: {
    symbol: 'CL$',
    name: 'Chilean Peso',
    symbol_native: '$',
    decimal_digits: 0,
    rounding: 0,
    name_plural: 'Chilean pesos',
  },
  [AllCurrencyEnum.Cny]: {
    symbol: 'CN¥',
    name: 'Chinese Yuan',
    symbol_native: 'CN¥',
    decimal_digits: 2,
    rounding: 0,
    name_plural: 'Chinese yuan',
  },
  [AllCurrencyEnum.Cop]: {
    symbol: 'CO$',
    name: 'Colombian Peso',
    symbol_native: '$',
    decimal_digits: 0,
    rounding: 0,
    name_plural: 'Colombian pesos',
  },
  [AllCurrencyEnum.Crc]: {
    symbol: '₡',
    name: 'Costa Rican Colón',
    symbol_native: '₡',
    decimal_digits: 0,
    rounding: 0,
    name_plural: 'Costa Rican colóns',
  },
  [AllCurrencyEnum.Cve]: {
    symbol: 'CV$',
    name: 'Cape Verdean Escudo',
    symbol_native: 'CV$',
    decimal_digits: 2,
    rounding: 0,
    name_plural: 'Cape Verdean escudos',
  },
  [AllCurrencyEnum.Czk]: {
    symbol: 'Kč',
    name: 'Czech Republic Koruna',
    symbol_native: 'Kč',
    decimal_digits: 2,
    rounding: 0,
    name_plural: 'Czech Republic korunas',
  },
  [AllCurrencyEnum.Djf]: {
    symbol: 'Fdj',
    name: 'Djiboutian Franc',
    symbol_native: 'Fdj',
    decimal_digits: 0,
    rounding: 0,
    name_plural: 'Djiboutian francs',
  },
  [AllCurrencyEnum.Dkk]: {
    symbol: 'Dkr',
    name: 'Danish Krone',
    symbol_native: 'kr',
    decimal_digits: 2,
    rounding: 0,
    name_plural: 'Danish kroner',
  },
  [AllCurrencyEnum.Dop]: {
    symbol: 'RD$',
    name: 'Dominican Peso',
    symbol_native: 'RD$',
    decimal_digits: 2,
    rounding: 0,
    name_plural: 'Dominican pesos',
  },
  [AllCurrencyEnum.Dzd]: {
    symbol: 'DA',
    name: 'Algerian Dinar',
    symbol_native: 'د.ج.‏',
    decimal_digits: 2,
    rounding: 0,
    name_plural: 'Algerian dinars',
  },
  [AllCurrencyEnum.Egp]: {
    symbol: 'EGP',
    name: 'Egyptian Pound',
    symbol_native: 'ج.م.‏',
    decimal_digits: 2,
    rounding: 0,
    name_plural: 'Egyptian pounds',
  },
  [AllCurrencyEnum.Ern]: {
    symbol: 'Nfk',
    name: 'Eritrean Nakfa',
    symbol_native: 'Nfk',
    decimal_digits: 2,
    rounding: 0,
    name_plural: 'Eritrean nakfas',
  },
  [AllCurrencyEnum.Etb]: {
    symbol: 'Br',
    name: 'Ethiopian Birr',
    symbol_native: 'Br',
    decimal_digits: 2,
    rounding: 0,
    name_plural: 'Ethiopian birrs',
  },
  [AllCurrencyEnum.Gbp]: {
    symbol: '£',
    name: 'British Pound Sterling',
    symbol_native: '£',
    decimal_digits: 2,
    rounding: 0,
    name_plural: 'British pounds sterling',
  },
  [AllCurrencyEnum.Gel]: {
    symbol: 'GEL',
    name: 'Georgian Lari',
    symbol_native: 'GEL',
    decimal_digits: 2,
    rounding: 0,
    name_plural: 'Georgian laris',
  },
  [AllCurrencyEnum.Ghs]: {
    symbol: 'GH₵',
    name: 'Ghanaian Cedi',
    symbol_native: 'GH₵',
    decimal_digits: 2,
    rounding: 0,
    name_plural: 'Ghanaian cedis',
  },
  [AllCurrencyEnum.Gnf]: {
    symbol: 'FG',
    name: 'Guinean Franc',
    symbol_native: 'FG',
    decimal_digits: 0,
    rounding: 0,
    name_plural: 'Guinean francs',
  },
  [AllCurrencyEnum.Gtq]: {
    symbol: 'GTQ',
    name: 'Guatemalan Quetzal',
    symbol_native: 'Q',
    decimal_digits: 2,
    rounding: 0,
    name_plural: 'Guatemalan quetzals',
  },
  [AllCurrencyEnum.Hkd]: {
    symbol: 'HK$',
    name: 'Hong Kong Dollar',
    symbol_native: '$',
    decimal_digits: 2,
    rounding: 0,
    name_plural: 'Hong Kong dollars',
  },
  [AllCurrencyEnum.Hnl]: {
    symbol: 'HNL',
    name: 'Honduran Lempira',
    symbol_native: 'L',
    decimal_digits: 2,
    rounding: 0,
    name_plural: 'Honduran lempiras',
  },
  [AllCurrencyEnum.Hrk]: {
    symbol: 'kn',
    name: 'Croatian Kuna',
    symbol_native: 'kn',
    decimal_digits: 2,
    rounding: 0,
    name_plural: 'Croatian kunas',
  },
  [AllCurrencyEnum.Huf]: {
    symbol: 'Ft',
    name: 'Hungarian Forint',
    symbol_native: 'Ft',
    decimal_digits: 0,
    rounding: 0,
    name_plural: 'Hungarian forints',
  },
  [AllCurrencyEnum.Idr]: {
    symbol: 'Rp',
    name: 'Indonesian Rupiah',
    symbol_native: 'Rp',
    decimal_digits: 0,
    rounding: 0,
    name_plural: 'Indonesian rupiahs',
  },
  [AllCurrencyEnum.Ils]: {
    symbol: '₪',
    name: 'Israeli New Sheqel',
    symbol_native: '₪',
    decimal_digits: 2,
    rounding: 0,
    name_plural: 'Israeli new sheqels',
  },
  [AllCurrencyEnum.Inr]: {
    symbol: 'Rs',
    name: 'Indian Rupee',
    symbol_native: 'টকা',
    decimal_digits: 2,
    rounding: 0,
    name_plural: 'Indian rupees',
  },
  [AllCurrencyEnum.Iqd]: {
    symbol: 'IQD',
    name: 'Iraqi Dinar',
    symbol_native: 'د.ع.‏',
    decimal_digits: 0,
    rounding: 0,
    name_plural: 'Iraqi dinars',
  },
  [AllCurrencyEnum.Irr]: {
    symbol: 'IRR',
    name: 'Iranian Rial',
    symbol_native: '﷼',
    decimal_digits: 0,
    rounding: 0,
    name_plural: 'Iranian rials',
  },
  [AllCurrencyEnum.Isk]: {
    symbol: 'Ikr',
    name: 'Icelandic Króna',
    symbol_native: 'kr',
    decimal_digits: 0,
    rounding: 0,
    name_plural: 'Icelandic krónur',
  },
  [AllCurrencyEnum.Jmd]: {
    symbol: 'J$',
    name: 'Jamaican Dollar',
    symbol_native: '$',
    decimal_digits: 2,
    rounding: 0,
    name_plural: 'Jamaican dollars',
  },
  [AllCurrencyEnum.Jod]: {
    symbol: 'JD',
    name: 'Jordanian Dinar',
    symbol_native: 'د.أ.‏',
    decimal_digits: 3,
    rounding: 0,
    name_plural: 'Jordanian dinars',
  },
  [AllCurrencyEnum.Jpy]: {
    symbol: '¥',
    name: 'Japanese Yen',
    symbol_native: '￥',
    decimal_digits: 0,
    rounding: 0,
    name_plural: 'Japanese yen',
  },
  [AllCurrencyEnum.Kes]: {
    symbol: 'Ksh',
    name: 'Kenyan Shilling',
    symbol_native: 'Ksh',
    decimal_digits: 2,
    rounding: 0,
    name_plural: 'Kenyan shillings',
  },
  [AllCurrencyEnum.Khr]: {
    symbol: 'KHR',
    name: 'Cambodian Riel',
    symbol_native: '៛',
    decimal_digits: 2,
    rounding: 0,
    name_plural: 'Cambodian riels',
  },
  [AllCurrencyEnum.Kmf]: {
    symbol: 'CF',
    name: 'Comorian Franc',
    symbol_native: 'FC',
    decimal_digits: 0,
    rounding: 0,
    name_plural: 'Comorian francs',
  },
  [AllCurrencyEnum.Krw]: {
    symbol: '₩',
    name: 'South Korean Won',
    symbol_native: '₩',
    decimal_digits: 0,
    rounding: 0,
    name_plural: 'South Korean won',
  },
  [AllCurrencyEnum.Kwd]: {
    symbol: 'KD',
    name: 'Kuwaiti Dinar',
    symbol_native: 'د.ك.‏',
    decimal_digits: 3,
    rounding: 0,
    name_plural: 'Kuwaiti dinars',
  },
  [AllCurrencyEnum.Kzt]: {
    symbol: 'KZT',
    name: 'Kazakhstani Tenge',
    symbol_native: 'тңг.',
    decimal_digits: 2,
    rounding: 0,
    name_plural: 'Kazakhstani tenges',
  },
  [AllCurrencyEnum.Lbp]: {
    symbol: 'L.L.',
    name: 'Lebanese Pound',
    symbol_native: 'ل.ل.‏',
    decimal_digits: 0,
    rounding: 0,
    name_plural: 'Lebanese pounds',
  },
  [AllCurrencyEnum.Lkr]: {
    symbol: 'SLRs',
    name: 'Sri Lankan Rupee',
    symbol_native: 'SL Re',
    decimal_digits: 2,
    rounding: 0,
    name_plural: 'Sri Lankan rupees',
  },
  [AllCurrencyEnum.Lyd]: {
    symbol: 'LD',
    name: 'Libyan Dinar',
    symbol_native: 'د.ل.‏',
    decimal_digits: 3,
    rounding: 0,
    name_plural: 'Libyan dinars',
  },
  [AllCurrencyEnum.Mad]: {
    symbol: 'MAD',
    name: 'Moroccan Dirham',
    symbol_native: 'د.م.‏',
    decimal_digits: 2,
    rounding: 0,
    name_plural: 'Moroccan dirhams',
  },
  [AllCurrencyEnum.Mdl]: {
    symbol: 'MDL',
    name: 'Moldovan Leu',
    symbol_native: 'MDL',
    decimal_digits: 2,
    rounding: 0,
    name_plural: 'Moldovan lei',
  },
  [AllCurrencyEnum.Mga]: {
    symbol: 'MGA',
    name: 'Malagasy Ariary',
    symbol_native: 'MGA',
    decimal_digits: 0,
    rounding: 0,
    name_plural: 'Malagasy Ariaries',
  },
  [AllCurrencyEnum.Mkd]: {
    symbol: 'MKD',
    name: 'Macedonian Denar',
    symbol_native: 'MKD',
    decimal_digits: 2,
    rounding: 0,
    name_plural: 'Macedonian denari',
  },
  [AllCurrencyEnum.Mmk]: {
    symbol: 'MMK',
    name: 'Myanma Kyat',
    symbol_native: 'K',
    decimal_digits: 0,
    rounding: 0,
    name_plural: 'Myanma kyats',
  },
  [AllCurrencyEnum.Mop]: {
    symbol: 'MOP$',
    name: 'Macanese Pataca',
    symbol_native: 'MOP$',
    decimal_digits: 2,
    rounding: 0,
    name_plural: 'Macanese patacas',
  },
  [AllCurrencyEnum.Mur]: {
    symbol: 'MURs',
    name: 'Mauritian Rupee',
    symbol_native: 'MURs',
    decimal_digits: 0,
    rounding: 0,
    name_plural: 'Mauritian rupees',
  },
  [AllCurrencyEnum.Mxn]: {
    symbol: 'MX$',
    name: 'Mexican Peso',
    symbol_native: '$',
    decimal_digits: 2,
    rounding: 0,
    name_plural: 'Mexican pesos',
  },
  [AllCurrencyEnum.Myr]: {
    symbol: 'RM',
    name: 'Malaysian Ringgit',
    symbol_native: 'RM',
    decimal_digits: 2,
    rounding: 0,
    name_plural: 'Malaysian ringgits',
  },
  [AllCurrencyEnum.Mzn]: {
    symbol: 'MTn',
    name: 'Mozambican Metical',
    symbol_native: 'MTn',
    decimal_digits: 2,
    rounding: 0,
    name_plural: 'Mozambican meticals',
  },
  [AllCurrencyEnum.Nad]: {
    symbol: 'N$',
    name: 'Namibian Dollar',
    symbol_native: 'N$',
    decimal_digits: 2,
    rounding: 0,
    name_plural: 'Namibian dollars',
  },
  [AllCurrencyEnum.Ngn]: {
    symbol: '₦',
    name: 'Nigerian Naira',
    symbol_native: '₦',
    decimal_digits: 2,
    rounding: 0,
    name_plural: 'Nigerian nairas',
  },
  [AllCurrencyEnum.Nio]: {
    symbol: 'C$',
    name: 'Nicaraguan Córdoba',
    symbol_native: 'C$',
    decimal_digits: 2,
    rounding: 0,
    name_plural: 'Nicaraguan córdobas',
  },
  [AllCurrencyEnum.Nok]: {
    symbol: 'Nkr',
    name: 'Norwegian Krone',
    symbol_native: 'kr',
    decimal_digits: 2,
    rounding: 0,
    name_plural: 'Norwegian kroner',
  },
  [AllCurrencyEnum.Npr]: {
    symbol: 'NPRs',
    name: 'Nepalese Rupee',
    symbol_native: 'नेरू',
    decimal_digits: 2,
    rounding: 0,
    name_plural: 'Nepalese rupees',
  },
  [AllCurrencyEnum.Nzd]: {
    symbol: 'NZ$',
    name: 'New Zealand Dollar',
    symbol_native: '$',
    decimal_digits: 2,
    rounding: 0,
    name_plural: 'New Zealand dollars',
  },
  [AllCurrencyEnum.Omr]: {
    symbol: 'OMR',
    name: 'Omani Rial',
    symbol_native: 'ر.ع.‏',
    decimal_digits: 3,
    rounding: 0,
    name_plural: 'Omani rials',
  },
  [AllCurrencyEnum.Pab]: {
    symbol: 'B/.',
    name: 'Panamanian Balboa',
    symbol_native: 'B/.',
    decimal_digits: 2,
    rounding: 0,
    name_plural: 'Panamanian balboas',
  },
  [AllCurrencyEnum.Pen]: {
    symbol: 'S/.',
    name: 'Peruvian Nuevo Sol',
    symbol_native: 'S/.',
    decimal_digits: 2,
    rounding: 0,
    name_plural: 'Peruvian nuevos soles',
  },
  [AllCurrencyEnum.Php]: {
    symbol: '₱',
    name: 'Philippine Peso',
    symbol_native: '₱',
    decimal_digits: 2,
    rounding: 0,
    name_plural: 'Philippine pesos',
  },
  [AllCurrencyEnum.Pkr]: {
    symbol: 'PKRs',
    name: 'Pakistani Rupee',
    symbol_native: '₨',
    decimal_digits: 0,
    rounding: 0,
    name_plural: 'Pakistani rupees',
  },
  [AllCurrencyEnum.Pln]: {
    symbol: 'zł',
    name: 'Polish Zloty',
    symbol_native: 'zł',
    decimal_digits: 2,
    rounding: 0,
    name_plural: 'Polish zlotys',
  },
  [AllCurrencyEnum.Pyg]: {
    symbol: '₲',
    name: 'Paraguayan Guarani',
    symbol_native: '₲',
    decimal_digits: 0,
    rounding: 0,
    name_plural: 'Paraguayan guaranis',
  },
  [AllCurrencyEnum.Qar]: {
    symbol: 'QR',
    name: 'Qatari Rial',
    symbol_native: 'ر.ق.‏',
    decimal_digits: 2,
    rounding: 0,
    name_plural: 'Qatari rials',
  },
  [AllCurrencyEnum.Ron]: {
    symbol: 'RON',
    name: 'Romanian Leu',
    symbol_native: 'RON',
    decimal_digits: 2,
    rounding: 0,
    name_plural: 'Romanian lei',
  },
  [AllCurrencyEnum.Rsd]: {
    symbol: 'din.',
    name: 'Serbian Dinar',
    symbol_native: 'дин.',
    decimal_digits: 0,
    rounding: 0,
    name_plural: 'Serbian dinars',
  },
  [AllCurrencyEnum.Rub]: {
    symbol: 'RUB',
    name: 'Russian Ruble',
    symbol_native: '₽.',
    decimal_digits: 2,
    rounding: 0,
    name_plural: 'Russian rubles',
  },
  [AllCurrencyEnum.Rwf]: {
    symbol: 'RWF',
    name: 'Rwandan Franc',
    symbol_native: 'FR',
    decimal_digits: 0,
    rounding: 0,
    name_plural: 'Rwandan francs',
  },
  [AllCurrencyEnum.Sar]: {
    symbol: 'SR',
    name: 'Saudi Riyal',
    symbol_native: 'ر.س.‏',
    decimal_digits: 2,
    rounding: 0,
    name_plural: 'Saudi riyals',
  },
  [AllCurrencyEnum.Sdg]: {
    symbol: 'SDG',
    name: 'Sudanese Pound',
    symbol_native: 'SDG',
    decimal_digits: 2,
    rounding: 0,
    name_plural: 'Sudanese pounds',
  },
  [AllCurrencyEnum.Sek]: {
    symbol: 'Skr',
    name: 'Swedish Krona',
    symbol_native: 'kr',
    decimal_digits: 2,
    rounding: 0,
    name_plural: 'Swedish kronor',
  },
  [AllCurrencyEnum.Sgd]: {
    symbol: 'S$',
    name: 'Singapore Dollar',
    symbol_native: '$',
    decimal_digits: 2,
    rounding: 0,
    name_plural: 'Singapore dollars',
  },
  [AllCurrencyEnum.Sos]: {
    symbol: 'Ssh',
    name: 'Somali Shilling',
    symbol_native: 'Ssh',
    decimal_digits: 0,
    rounding: 0,
    name_plural: 'Somali shillings',
  },
  [AllCurrencyEnum.Syp]: {
    symbol: 'SY£',
    name: 'Syrian Pound',
    symbol_native: 'ل.س.‏',
    decimal_digits: 0,
    rounding: 0,
    name_plural: 'Syrian pounds',
  },
  [AllCurrencyEnum.Thb]: {
    symbol: '฿',
    name: 'Thai Baht',
    symbol_native: '฿',
    decimal_digits: 2,
    rounding: 0,
    name_plural: 'Thai baht',
  },
  [AllCurrencyEnum.Tnd]: {
    symbol: 'DT',
    name: 'Tunisian Dinar',
    symbol_native: 'د.ت.‏',
    decimal_digits: 3,
    rounding: 0,
    name_plural: 'Tunisian dinars',
  },
  [AllCurrencyEnum.Top]: {
    symbol: 'T$',
    name: 'Tongan Paʻanga',
    symbol_native: 'T$',
    decimal_digits: 2,
    rounding: 0,
    name_plural: 'Tongan paʻanga',
  },
  [AllCurrencyEnum.Try]: {
    symbol: 'TL',
    name: 'Turkish Lira',
    symbol_native: 'TL',
    decimal_digits: 2,
    rounding: 0,
    name_plural: 'Turkish Lira',
  },
  [AllCurrencyEnum.Ttd]: {
    symbol: 'TT$',
    name: 'Trinidad and Tobago Dollar',
    symbol_native: '$',
    decimal_digits: 2,
    rounding: 0,
    name_plural: 'Trinidad and Tobago dollars',
  },
  [AllCurrencyEnum.Twd]: {
    symbol: 'NT$',
    name: 'New Taiwan Dollar',
    symbol_native: 'NT$',
    decimal_digits: 2,
    rounding: 0,
    name_plural: 'New Taiwan dollars',
  },
  [AllCurrencyEnum.Tzs]: {
    symbol: 'TSh',
    name: 'Tanzanian Shilling',
    symbol_native: 'TSh',
    decimal_digits: 0,
    rounding: 0,
    name_plural: 'Tanzanian shillings',
  },
  [AllCurrencyEnum.Uah]: {
    symbol: '₴',
    name: 'Ukrainian Hryvnia',
    symbol_native: '₴',
    decimal_digits: 2,
    rounding: 0,
    name_plural: 'Ukrainian hryvnias',
  },
  [AllCurrencyEnum.Ugx]: {
    symbol: 'USh',
    name: 'Ugandan Shilling',
    symbol_native: 'USh',
    decimal_digits: 0,
    rounding: 0,
    name_plural: 'Ugandan shillings',
  },
  [AllCurrencyEnum.Uyu]: {
    symbol: '$U',
    name: 'Uruguayan Peso',
    symbol_native: '$',
    decimal_digits: 2,
    rounding: 0,
    name_plural: 'Uruguayan pesos',
  },
  [AllCurrencyEnum.Uzs]: {
    symbol: 'UZS',
    name: 'Uzbekistan Som',
    symbol_native: 'UZS',
    decimal_digits: 0,
    rounding: 0,
    name_plural: 'Uzbekistan som',
  },
  [AllCurrencyEnum.Vef]: {
    symbol: 'Bs.F.',
    name: 'Venezuelan Bolívar',
    symbol_native: 'Bs.F.',
    decimal_digits: 2,
    rounding: 0,
    name_plural: 'Venezuelan bolívars',
  },
  [AllCurrencyEnum.Vnd]: {
    symbol: '₫',
    name: 'Vietnamese Dong',
    symbol_native: '₫',
    decimal_digits: 0,
    rounding: 0,
    name_plural: 'Vietnamese dong',
  },
  [AllCurrencyEnum.Xaf]: {
    symbol: 'FCFA',
    name: 'CFA Franc BEAC',
    symbol_native: 'FCFA',
    decimal_digits: 0,
    rounding: 0,
    name_plural: 'CFA francs BEAC',
  },
  [AllCurrencyEnum.Xof]: {
    symbol: 'CFA',
    name: 'CFA Franc BCEAO',
    symbol_native: 'CFA',
    decimal_digits: 0,
    rounding: 0,
    name_plural: 'CFA francs BCEAO',
  },
  [AllCurrencyEnum.Yer]: {
    symbol: 'YR',
    name: 'Yemeni Rial',
    symbol_native: 'ر.ي.‏',
    decimal_digits: 0,
    rounding: 0,
    name_plural: 'Yemeni rials',
  },
  [AllCurrencyEnum.Zar]: {
    symbol: 'R',
    name: 'South African Rand',
    symbol_native: 'R',
    decimal_digits: 2,
    rounding: 0,
    name_plural: 'South African rand',
  },
  [AllCurrencyEnum.Zwl]: {
    symbol: 'ZWL$',
    name: 'Zimbabwean Dollar',
    symbol_native: 'ZWL$',
    decimal_digits: 0,
    rounding: 0,
    name_plural: 'Zimbabwean Dollar',
  },
};
