query campaignForOffer($campaignId: ID!) {
  getSelectedAdCampaignDetails(campaignId: $campaignId) {
    status
    paymentRef {
      paymentStatus
    }
    createdBy {
      firstName
    }
    ...CampaignOfferBasic
  }
}
