query getPostsByChamberId(
  $chamberId: ID!
  $limit: Int
  $offset: Int
  $sort: SortType
  $filter: PostFilter
) {
  getPostsByChamberId(
    chamberId: $chamberId
    limit: $limit
    offset: $offset
    sort: $sort
    filter: $filter
  ) {
    data {
      ...PostItem
    }
    count
  }
}
