query getSpotLightChambers(
  $filter: SpotlightChamberFilters
  $offset: Int
  $limit: Int
) {
  getSpotLightChambers(filter: $filter, offset: $offset, limit: $limit) {
    data {
      _id
      name
      title
      type
      projectType
      description
      profileImage
      followersCount
      status
      uid {
        _id
        firstName
        lastName
        title
        userStatus
        location
        profile {
          profilePicture
        }
      }
      category {
        _id
        name
      }
    }
    count
  }
}
