query getUserSubmittedOnboardingQuestionsAndAnswers($userId: ID) {
  getUserSubmittedOnboardingQuestionsAndAnswers(userId: $userId) {
    userId
    userSelection {
      _id
      questionId
      answer
    }
  }
}
