query getUserInvoiceLineItemList($filter: InvoiceSearchInput!) {
  getUserInvoiceLineItemList(filter: $filter) {
    data {
      id
      description
      quantity
      unitPrice
      taxRate
      taxLabel
      currency
      amount
    }
    count
  }
}
