query payAsYouGoSetupCounters(
  $noumDetailInput: NoumTransactionDetailInputType!
) {
  getNoumTransactionFeeDetails(noumDetailInput: $noumDetailInput) {
    subscription_id {
      ...NoumSetupCounter
    }
  }
}
