query receivedNoumConnectionInvites($limit: Int, $offset: Int) {
  receivedNoumConnectionInvites(input: { limit: $limit, offset: $offset }) {
    count
    data {
      ...NoumPendingConnection
    }
  }
}
