query userReferralEntry($productKey: String) {
  userReferralEntry(productKey: $productKey) {
    maxAllowedCount
    ownerUserId {
      ...UserBasicOutput
    }
    referralCode
    usedBy {
      ...UserBasicOutput
      createdAt
    }
    usedCount
  }
}
